### ISSUE TITLE
Setup hyphosis

### ISSUE THREAD

**Issue by hychen** [g0v/ggv#1]

**Comment by wenchen** [comment]
目前已經完成初步的部屬，測試位置在 [kuansim.org](https://kuansim.org/)

目前未成功部署的部分如下
1. Email 認證
2. oAuth

**Comment by wenchen** [comment]
目前已經設定好
1. Email認證: 目前使用gmail進行測試
2. oauth: 這是給第三方網站用的, 假設有第三方網站需要oauth, 仍需要透過修改設定檔開放給第三方網站使用
