### ISSUE TITLE
Survey PDF annotation

### ISSUE THREAD

**Issue by caasi** [g0v/ggv#2]
Hypothesis 可以在 PDF [被 OCR 之後](https://web.hypothes.is/blog/annotating-ocred-pdfs/)，對它上 annotation 。

* 可以在沒有 OCR 時加上 annotation 嗎？
* 有沒有替代方案？

**Comment by caasi** [comment]
目前的心得如下，[也記載在 YA0H 那裏](https://github.com/g0v/ambassador/blob/master/docs/README.md#2017-10-24)：

回到 web annotation 。除了 YA0H 以外， hychen 的 GGV 也用得上。 Hypothesis 的 [client][hypothesis/client] 在 pdf 上只支援附註與 highlight 。沒辦法畫框框，自然沒有辦法在未經過 OCR 的文件上註記。

加上附註的 selectors 像這樣：

```
[{
  type: 'TextPositionSelector',
  start: 0,
  end: 42
}, {
  type: 'TextQuoteSelector',
  exact: 'A History of Haskell:Being Lazy With Class',
  prefix: '  ↵        ↵↵        ↵          ',
  suffix: 'April 16, 2007Paul HudakYale Uni'
}]
``` 

和 html 上的附註不太一樣。 html 上會多一個 range selector ：

```
{
  type: 'RangeSelector',
  startContainer: '/div[2]/article[1]/div[1]/p[3]',
  startOffset: 8,
  endContainer: '/div[2]/article[1]/div[1]/p[3]',
  endOffset: 12
}
```

另外 Hypothesis 的 range selector 和 [web annotation data model][WADM] 中定義的不太一樣，不知道哪天會遇上按著 WADM 實作的版本？

下一步是找看看有沒有辦法在 pdf 上，實現畫框框(fragment selector)上註解。

[hypothesis/client]: https://github.com/hypothesis/client
[WADM]: https://www.w3.org/TR/annotation-model/

* * *

Hypothesis 重用了來自 [Open Annotation][openannotation] 的成果。

逛一逛會發現如果想自己搭 annotation 產品，可以用他們開發的 [Annotator][annotatorjs.org] 。而且 Annotator 上能開發 plugins 。如果想要畫框框上註解，目前有一個專門做圖片註解的 plugin 叫做 [annotator-imgselect][annotator-imgselect] ，還有個專門做圖片註解的服務叫做 [annotorious][annotorious] 。

如果我得在 pdf viewer 上實現類似功能，大概會先疊上一層 Canvas ，再開始做和圖片註解一樣的事。

[openannotation]: https://github.com/openannotation
[annotatorjs.org]: http://annotatorjs.org/
[annotator-imgselect]: https://github.com/emory-lits-labs/annotator-imgselect
[annotorious]: https://github.com/annotorious/annotorious

**Comment by caasi** [comment]
另外， hypothesis/client 關於 selector 的程式應該都在 [src/annotator/anchoring](https://github.com/hypothesis/client/tree/master/src/annotator/anchoring) 。

從 `pdf.coffee` 中可以看到完全沒用到 [`FragmentAnchor`][dom-anchor-fragment] ，而用到 `FragmentAnchor` 的 `html.coffee` ，也只是用它來把 DOM `Range` 轉成 fragment selector ，不是我們要的 pdf fragment 。

[dom-anchor-fragment]: https://github.com/tilgovi/dom-anchor-fragment

**Comment by wenchen** [comment]
在圖上畫框，假設我們要從中萃取資訊，我們最後還是得把圖片擷取下來做OCR？

**Comment by caasi** [comment]
> 在圖上畫框，假設我們要從中萃取資訊，我們最後還是得把圖片擷取下來做OCR？

對啊。 0rz

但至少有了 x, y, w, h 。

**Comment by wenchen** [comment]
要不要先找地方存圖片，然後找志工做，工人智慧OCR ~~

**Comment by hychen** [comment]
close because we move our repo to github.com/g0vggv
