### ISSUE TITLE
Customize annotation client

### ISSUE THREAD

**Issue by caasi** [g0v/ggv#3]
開個 issue 問問計劃想做怎樣的客製化前端？只有 annotation 功能嗎？還是混合其他功能？

不管怎樣， @caasi 還是得看 hypothesis/client 怎麼跟 pdf.js 溝通 XD

**Comment by hychen** [comment]
先處理這樣

1. 可以自訂標籤集
2. 用自訂標籤集來做 annotation

**Comment by hychen** [comment]
先以可以標出ORID

**Comment by hychen** [comment]
@caasi  先是先試著在這下面 contextmenu 上加上 四個按鈕分別是 "事實" "感覺" "詮釋" "想法"

<img width="396" alt="2017-11-10 5 41 56" src="https://user-images.githubusercontent.com/38706/32652234-3e3c9efa-c5c9-11e7-8337-9efc51685c51.png">

使用者 click 後會對那條 highlight 的句子上 Tag 。

**Comment by caasi** [comment]
好主意，我還在想怎麼改 tag 選單，而沒有想這美妙的解法。

但是 Annotate 跟 Highlight 還要留著？

**Comment by hychen** [comment]
直接去掉好了

從我的 iPhone 傳送

**Comment by caasi** [comment]
@wenchen 可以幫我看看，這個[修改過的 client ][caasi-fork]，是否能和 h 合作，正確為 annotation 加上 tag 嗎？

[caasi-fork]: https://github.com/caasi/client/commit/10592180f60e2e0b32921e2b169e35a383817fa6

現在會加上像是 `['ORID', 'ORID-objective']` 這樣的 tag 。

**Comment by hychen** [comment]
close because we move our repo to github.com/g0vggv
